### ISSUE TITLE
 Email template

### ISSUE THREAD

**Issue by skimmerk** [teddywilson/defund12.org#106]
Hello,  I was wondering if one can be created for Canada? Specifically Toronto.

Thank you.

**Comment by teddywilson** [comment]
We won't create one on our own but feel free to submit a new request with the required information:

- A subject message for the email
- A list of emails (at least one) for the government officials you’d like to receive the message
- A detailed message concerning the budgeting decisions that are at stake in your community
See our current links for examples at https://defund12.org.

Since this request doesn't meet our issue criteria I will have to close it out. But feel free to reopen a new one!
