### ISSUE TITLE
Add Chicago

### ISSUE THREAD

**Issue by zestylady** [teddywilson/defund12.org#13]

**Comment by erikob05** [comment]
List of emails of elected officials in Chicago:
[Cook County Directory of Elected Officials.xlsx](https://github.com/teddywilson/defund12.org/files/4732924/Cook.County.Directory.of.Elected.Officials.xlsx)

**Comment by averymcguirt** [comment]
We are currently processing a lot of requests--it would greatly speed up our addition of Chicago if you could draft a detailed (but succinct) message! Feel free to use existing messages ( defund12.org ) 

Thank you!

**Comment by jdm437** [comment]
**Subject**: Commit to Defunding and Reforming CPD

**Emails**: ward01@cityofchicago.org, ward02@cityofchicago.org, ward03@cityofchicago.org, ward04@cityofchicago.org, ward05@cityofchicago.org, ward06@cityofchicago.org, ward07@cityofchicago.org, ward08@cityofchicago.org, ward09@cityofchicago.org, ward10@cityofchicago.org, ward11@cityofchicago.org, ward12@cityofchicago.org, ward13@cityofchicago.org, ward14@cityofchicago.org, ward15@cityofchicago.org, ward16@cityofchicago.org, ward17@cityofchicago.org, ward18@cityofchicago.org, 
ward19@cityofchicago.org, ward20@cityofchicago.org, ward21@cityofchicago.org, ward22@cityofchicago.org, ward23@cityofchicago.org, ward24@cityofchicago.org, ward26@cityofchicago.org, ward27chicago@gmail.com, ward28@cityofchicago.org, ward29@cityofchicago.org, ward30@cityofchicago.org, ward31@cityofchicago.org, ward32@cityofchicago.org, ward33@cityofchicago.org, ward34@cityofchicago.org, 
ward35@cityofchicago.org, ward36@cityofchicago.org, ward37@cityofchicago.org,
ward38@cityofchicago.org, ward39@cityofchicago.org, ward40@cityofchicago.org, ward41@cityofchicago.org, ward42@cityofchicago.org, ward43@cityofchicago.org, ward44@cityofchicago.org, ward45@cityofchicago.org, ward46@cityofchicago.org, ward47@cityofchicago.org, ward48@cityofchicago.org, ward49@cityofchicago.org, ward50@cityofchicago.org

**Message**:

Hello,   

My name is [NAME] and I am a resident of [NEIGHBORHOOD/CITY]. I am extremely concerned with the City of Chicago’s inordinate investment in the Chicago Police Department (CPD) at the expense of critical youth, education, and health services. As demonstrated by ongoing peaceful protests and a 2019 Gallup poll, a majority of individuals living in Chicago view the police negatively. 

I am therefore writing to demand that the City Council vote to reapportion funds allocated to the CPD to support evidence-based programs and services that, unlike increased police presence, promote the well-being of citizens and reduce crime. It is morally reprehensible to dedicate 40% of the City’s operating budget (approximately $4 million per day) towards policing while thousands of citizens are homeless and many more lack access to essential services, including clean running water and necessary mental health resources. 

I also urge the City Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity. As set forth by Black Lives Matter of Chicago, I ask that Homan Square be immediately closed (a site where extrajudicial police interrogations are known to occur), that an elected Civilian Police Accountability Council be established with real reform powers, and that abusive cops be fired and criminally charged. Ending the unfair and secretive internal CPD grievance review process would be a good first step in achieving this goal.

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents and take immediate action to address their concerns. 

Thank you,
[NAME]

**Comment by averymcguirt** [comment]
Beautiful. We will add this ASAP!

Thanks for your contribution.

**Comment by jdm437** [comment]
One minor issue: ward27chicago@gmail.com should be changed to ward27@cityofchicago.org. Thanks all for your dedication and fast work on this.
