### ISSUE TITLE
Contributor Discord

### ISSUE THREAD

**Issue by Ceshion** [teddywilson/defund12.org#145]
I'm noticing several templates being added multiple times, let's coordinate on Discord?

https://discord.gg/wJ6ZGv

**Comment by teddywilson** [comment]
We actually are starting a slack channel now. What are your thoughts on this instead? I'm not familiar with discord, and neither is the rest of the team.

**Comment by Ceshion** [comment]
Slack is good too! I can't speak for everyone who did join it of course, but I'd be happy to move there.

**Comment by Ceshion** [comment]
@teddywilson how do you think is best to arrange access?

**Comment by teddywilson** [comment]
Hey, so we agreed that for community conversation, it may be better routed to discord. Join the conversation here: https://discord.gg/YMxndzd

And please share with anyone else you would like to invite! Information about joining the conversation can be found in the updated README. If we decide to open up slack, I will let you know, otherwise I will close this out.
