### ISSUE TITLE
Arcata/Eureka, CA Police - Justice for Josiah Lawson

### ISSUE THREAD

**Issue by ang3lph4se** [teddywilson/defund12.org#408]
Hello, I'm from northern california and am very thankful for the template you helped me with for eureka, ca.  I saw the template which was made for Breonna Taylor and was hoping i could ask for assistance in creating one for Josiah Lawson who was murdered in 2017 by a white supremicist but his killer was never charged and the police botched the investigation.  There have been many documentaries and stories made demanding justice for his unsolved murder. His mother, Charmaine Lawson, is still fighting for the justice of her sons death and working very hard. She made a new donation page https://www.gofundme.com/f/justice-for-josiah-litigation-assistance?utm_medium=copy_link&utm_source=customer&utm_campaign=p_lico+share-sheet to start collecting for the discovery phase of the litigation process. 

I have trouble bringing all the necessary components together at once but i want to do everything i can do give awareness to this case so she may get the justice and peace she deserves.

https://www.justiceforjosiahlawson.com/
https://www.youtube.com/watch?v=v6uzA83_y5c

if you need any more information to construct the template please let me know

**Comment by teddywilson** [comment]
Hey, we are not assisting in creating templates, only bringing ones in from the community. I'm going to close out this issue, because we are only accepting issues that contain all of the valid information:

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community 

Please read more about our email style guidelines [here](https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide).

If this information is copied from an external source *please* provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!
