### ISSUE TITLE
Please add Richmond, VA

### ISSUE THREAD

**Issue by northweeks** [teddywilson/defund12.org#415]
We need these confederate monuments gone and the police defunded!

**Comment by teddywilson** [comment]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community 

Please read more about our email style guidelines [here](https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide).

If this information is copied from an external source *please* provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!
