### ISSUE TITLE
Add San Francisco & Oakland, CA, please!

### ISSUE THREAD

**Issue by theakristinj** [teddywilson/defund12.org#44]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by Akinyi95** [comment]
Subject: We Demand a Peoples Budget for Oakland

List of Emails: officeofthemayor@oaklandnet.com, KJones3@Oaklandca.gov, DJeffress@oaklandca.gov, AMTellez@oaklandca.gov, info@oaklandcityattorney.org, lreid@oaklandnet.com, District6@oaklandca.gov, Ngallo@oaklandca.gov, district4@oaklandca.gov, LMcElhaney@oaklandca.gov, nfbas@oaklandca.gov, dkalb@oaklandca.gov

Message:
Hi my name is [YOUR NAME] and I am a resident of Oakland, CA. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community well being and redirects funding away from the police.

Now, more than ever, it is important that we take a hard look at how our systems are failing us so that we can understand why our Oakland community is so upset. Rather than funnel money towards a sprawling and inefficient police department while chanting “reform”, we demand to see that money put to use in our community through social programs that enrich our families, neighbors and friends. 

We are demanding that our voices be heard now, and that real change be made to the way this city allocates its resources. We hope that this is kept in mind when adopting the final balanced budget for the 2020-21 fiscal year on July 1.

Thank you for your time,

[YOUR NAME]  [YOUR EMAIL]
