### ISSUE TITLE
Atlanta, Georgia

### ISSUE THREAD

**Issue by mhaque32** [teddywilson/defund12.org#5]

**Comment by daltonwood** [comment]
via [instagram](https://www.instagram.com/p/CBBDtgcAgjB/)
Charles Bell: Fiscal Policy Chief - cebell@atlantaga.gov (404) 546-1033
Shawn A. Gabriel: Director Budget Admin - sagabriel@atlantaga.gov (404) 865-8442 ext. 66949

Hi, my name is [NAME] and I am a resident of [NEIGHBORHOOD]. I am asking to redirect money away from the Atlanta PD and into the following social services: [LIST - Community Development, COVID Relief, Education, Parks & Recreation]. I request that an emergency meeting be called before the fiscal year goes into effect in order to deny the mayor's proposed budget and reallocate these funds to resources the citizens can benefit from.

Additional numbers/emails for contacting daily:
Find your council member here: [link](http://egis.atlantaga.gov/app/home/index.html)
Call the financial division of Atlanta: (404) 330-6430
Call the Chief Financial Officer (Roosevelt Council Jr.): (404) 330-6453

FISCAL YEAR BEGINS JULY 1

**Comment by teddywilson** [comment]
Great! I'll get started on this one now. I'll close out the issue when it's live.

**Comment by daltonwood** [comment]
Awesome, thanks. I just updated with formatting.

**Comment by daltonwood** [comment]
**Same ig account posted info for surrounding Atlanta counties: [instagram](https://www.instagram.com/p/CBBDyXkgZfA/)**

Really important as urban sprawl is horrific here. Let me know if I can get you anything else, I'm actively seeking out more resources for this. Thank-you for defund12!

**Comment by daltonwood** [comment]
One more: [Looks like they're compiling everything in google slides here, may be easier for copying/pasting](https://docs.google.com/presentation/d/1i24LWYGDXAmXs8nZ-3rfuhYsMYBVfus9yGzUHQP7P70/mobilepresent#slide=id.g8632abb55c_1_16)

Contact info they're providing is atlantaresists@gmail.com

**Comment by averymcguirt** [comment]
This message is now live! https://defund12.org/atlanta
Thank you for your contribution.
As we receive more input we may edit or add more information/recipients.
