### ISSUE TITLE
Defund Phoenix police

### ISSUE THREAD

**Issue by dmorlaff** [teddywilson/defund12.org#64]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by cstrouse** [comment]
- Kate Gallego, Mayor (mayor.gallego@phoenix.gov)
- Thelda Williams (council.district.1@phoenix.gov)
- Jim Waring (council.district.2@phoenix.gov)
- Debra Stark (council.district.3@phoenix.gov)
- Laura Pastor (council.district.4@phoenix.gov)
- Betty Guardado, Vice Mayor (council.district.5@phoenix.gov)
- Sal DiCiccio (council.district.6@phoenix.gov)
- Michael Nowakowski (council.district.7@phoenix.gov)
- Carlos Garcia (council.district.8@phoenix.gov)

**Comment by teddywilson** [comment]
@cstrouse thank you for providing the list of recipients. Unfortunately, we will need a bit more information in order to proceed with this request. @dmorlaff, I'm going to close this one out, but please reopen the issue with an email, subject, and recipients (or the one's that @cstrouse has provided) and we will proceed forward!
