### ISSUE TITLE
Add Madison, WI please!

### ISSUE THREAD

**Issue by sarahkw13** [teddywilson/defund12.org#88]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by cstrouse** [comment]
- Barbara Harrington-McKinney, District 1 (district1@cityofmadison.com)
- Patrick W. Heck, District 2 (district2@cityofmadison.com)
- Lindsay Lemmer, District 3 (district3@cityofmadison.com)
- Michael E. Verveer, District 4 (district4@cityofmadison.com)
- Shiva Bidar, District 5 (district5@cityofmadison.com)
- Marsha A. Rummel, District 6 (district6@cityofmadison.com)
- Donna V. Moreland, District 7 (district7@cityofmadison.com)
- Max Prestigiacomo, District 8 (district8@cityofmadison.com)
- Paul E. Skidmore, District 9 (district9@cityofmadison.com)
- Zachary Henak, District 10 (district10@cityofmadison.com)
- Arvina Martin, District 11 (district11@cityofmadison.com)
- Syed Abbas, Council Vice President, District 12 (district12@cityofmadison.com)
- Tag Evers, District 13 (district13@cityofmadison.com)
- Sheri Carter, Council President, District 14 (district14@cityofmadison.com)
- Grant Foster, District 15 (district15@cityofmadison.com)
- Michael J. Tierney, District 16 (district16@cityofmadison.com)
- Samba Baldeh, District 17 (district17@cityofmadison.com)
- Rebecca Kemble, District 18 (district18@cityofmadison.com)
- Keith Furman, District 19 (district19@cityofmadison.com)
- Christian A. Albouras, District 20 (district20@cityofmadison.com)

**Comment by teddywilson** [comment]
Please provide the following information so we can move forward:

- Email subject
- Email body text

**Comment by ashdc98** [comment]
Subject: Defund MPD, Reallocate for Social Equity 🔗
Message (Don't forget to replace the [x]'s with your information!) 🔗 
Dear Madison Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY].

I am extremely concerned with the City of Madison’s inordinate investment in the Madison Police Department (MPD) at the expense of critical youth, education, and health services.

I am asking that the Madison City Council make a more overt and visible commitment to racial justice. I ask that the Council find ways to redirect money away from Madison Police Department’s overinflated budget and instead invest it into communities of color. I urge you to pressure the City Manager’s Office for an ethical reallocation of the city’s expenditures: away from MPD, and towards sectors that facilitate the dismantling of racial and class inequality.

Research shows that a living wage, access to health services and treatment, educational opportunities, and stable housing are far more successful at promoting safe communities than police or prisons. As such, I demand more aggressive financial support be directed to those areas.

The events of the last weeks have shown time and again that it is also critical that you implement enforceable controls on police tactics, and explicitly ban pervasive violent tactics–dangerous physical restraints, chemical weapons, and rubber bullets are all seriously dangerous and often lethal.

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents and take immediate action to address their concerns.

Can I count on you to consider an alternative budget that puts a focus on social service programs?

Thank you,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by sarahkw13** [comment]
You guys are amazing! Thank you!
