### ISSUE TITLE
Please add Honolulu, Hi!

### ISSUE THREAD

**Issue by mayumiishikawa** [teddywilson/defund12.org#89]

**Comment by cstrouse** [comment]
- **DISTRICT 1:** Kymberly Marcos Pine (kmpine@honolulu.gov)
- **DISTRICT 2:** Heidi Tsuneyoshi (htsuneyoshi@honolulu.gov)
- **DISTRICT 3:** Ikaika Anderson (ianderson@honolulu.gov)
- **DISTRICT 4:** Tommy Waters (tommy.waters@honolulu.gov)
- **DISTRICT 5:** Ann Kobayashi (akobayashi@honolulu.gov)
- **DISTRICT 6:** Carol Fukunaga (cafukunaga@honolulu.gov)
- **DISTRICT 7:** Joey Manahan (jmanahan@honolulu.gov)
- **DISTRICT 8:** Brandon Elefante (belefante@honolulu.gov)
- **DISTRICT 9:** Ron Menor (rmenor@honolulu.gov)

**Comment by carrieham** [comment]
@cstrouse thank you for providing the list of recipients. Unfortunately, we will need a bit more information in order to proceed with this request. @mayumiishikawa, I'm going to close this one out, but please reopen the issue with an email, subject, and recipients (or the ones that @cstrouse has provided) and we will proceed forward!
